# Generated by Django 6.0.2 on 2026-02-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
