# Generated by Django 6.0.2 on 2026-02-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-id'],
            },
        ),
    ]
